# Numpy 50本ノック

## PythonのNumPyとは
最初にPythonにおけるNumPyの役割やNumPyを使ってできることを解説します。
まずはNumPyで何ができるのかを理解しましょう。
### NumPyの役割
NumPyは機械学習やディープラーニングを行う際に使われる拡張ライブラリです。ベクトルや行列といった数学的対象を処理するのに便利なライブラリになっています。
基本的な計算処理であればNumPyを使わずともできますが、大量のデータを処理するような場合には処理が遅くなるため、高速な数値計算が必要な場合にはNumPyを使うことが多いです。
つまり、NumPyはベクトルや行列の計算を高速に処理するためのライブラリと覚えておけば大丈夫です。

### Numpyでできること
NumPyを使用することによって、ベクトルや行列の演算、乱数生成など様々なことができるようになります。通常のPythonで処理を行うよりもずっと早く処理できるので、大量のデータを扱う機械学習ではNumPyが利用されるのです。

基本的には、数値計算を高速で行うことができると覚えておけば問題ありません。

### 1. npという名前でnumpyパッケージをインポート 

In [1]:
import numpy as np

### 2. numpyの構成とバージョンを表示

In [2]:
print(np.__version__)
np.show_config()

1.13.3
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
atlas_3_10_blas_threads_info:
  NOT AVAILABLE
atlas_3_10_blas_info:
  NOT AVAILABLE
atlas_blas_threads_info:
  NOT AVAILABLE
atlas_blas_info:
  NOT AVAILABLE
blas_info:
    libraries = ['blas', 'blas']
    library_dirs = ['/usr/lib/x86_64-linux-gnu']
    include_dirs = ['/usr/local/include', '/usr/include']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['blas', 'blas']
    library_dirs = ['/usr/lib/x86_64-linux-gnu']
    include_dirs = ['/usr/local/include', '/usr/include']
    language = c
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
  NOT AVAILABLE
atlas_3_10_info:
  NOT AVAILABLE
atlas_threads_info:
  NOT AVAILABLE
atlas_info:
  NOT AVAILABLE
lapack_info:
    libraries = ['lapack', 'lapack']
    library_dirs = ['/usr/lib/x86_64-li

### 3. 配列を作る

#### 3.1 配列を作る

In [74]:
np.array([1, 2, 3])

array([1, 2, 3])

#### 3.2 要素がゼロの配列を作る

In [75]:
np.zeros(3, dtype=float)

array([ 0.,  0.,  0.])

#### 3.3 aと同じ形式の、要素がゼロの行列を作る

In [76]:
a = np.array([1, 2, 3])
np.zeros_like(a) 

array([0, 0, 0])

#### 3.4 要素が1の配列を作る

In [77]:
np.ones(3)

array([ 1.,  1.,  1.])

#### 3.5 単位行列を作る

In [78]:
np.eye(2)

array([[ 1.,  0.],
       [ 0.,  1.]])

#### 3.6 規則的な配列を作る

In [80]:
print(np.arange(0,2, 0.5)) # 始点、終点(アウトプットはこの値を含まない）、間隔を記載
print(np.linspace(1, 10, 10)) # 始点、終点(アウトプットはこの値を含む)、個数を記載

[ 0.   0.5  1.   1.5]
[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]


#### 3.7 サイズが10 ゼロベクトルの作成

In [4]:
Z = np.zeros(10)
print(Z)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


### 4. 様々な乱数の配列をつくる

#### 4.1 0.0以上、1.0未満の一様分布の乱数を生成

In [81]:
print(np.random.rand(2)) # 0〜1の乱数を2つ作成
print(np.random.rand(2, 2) )# 0〜1の乱数で2x2の行列を生成

[ 0.06890122  0.57304065]
[[ 0.6109665   0.83168801]
 [ 0.61687724  0.163494  ]]


#### 4.2 範囲での任意の整数の乱数を生成

In [82]:
np.random.randint(1, 7) # 1~７未満の範囲で任意の整数が返される

6

#### 4.3 平均0、分散1の標準正規分布に従う値を生成

In [84]:
print(np.random.randn())   # 値を一つ作成
print(np.random.randn(2, 2) )# 値を2×2行列で作成

-0.7633476128037319
[[-1.5684538  -0.76781873]
 [ 1.59506128  0.98528403]]


#### 4.4 正規分布の任意の平均・標準偏差を指定できる

In [85]:
np.random.normal(5, 1) # 平均5、標準偏差1の正規分布

4.463714263730363

#### 4.5 ランダムに要素を抽出

In [86]:
a = np.array(10)
np.random.choice(a) # 配列aの中からランダムに要素を抽出 

8

### 5. 配列の参照をする

#### 5.1 行列の次元数を参照

In [87]:
a = np.array([[1, 2 ,3],[4, 5, 6]])
a.ndim

2

#### 5.2 行列の要素数を参照

In [88]:
a = np.array([[1, 2 ,3],[4, 5, 6]])
a.size

6

#### 5.3 行・列数を参照

In [89]:
a = np.array([[1, 2 ,3],[4, 5, 6]])
a.shape

(2, 3)

#### 5.4 要素の型を参照

In [90]:
a = np.array([[1, 2 ,3],[4, 5, 6]])
a.dtype

dtype('int64')

#### 5.5 配列のp行q列目の要素の参照

In [91]:
a = np.array([1, 2, 3])
a[1] # 先頭を0番目とした際の1番目の値を参照

2

In [92]:
a[0:2] # 0番目から、２番目の一つ手前までを参照

array([1, 2])

In [93]:
b = np.array([[1, 2 ,3],[4, 5, 6]])
b[0,1] # 0行1列目を参照

2

In [95]:
b[:,1] # 1列目を参照

array([2, 5])

In [96]:
b[:,[1,2]] # 1,2列目を参照

array([[2, 3],
       [5, 6]])

### 6. 配列を操作する

#### 6.1 p行q列の配列に変換

In [97]:
a = np.array([[1, 2 ,3],[4, 5, 6]])
a.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

#### 6.2 p行q列の配列に変換し、変更された配列がもとの配列より大きければ、必要なだけ0で埋める

In [99]:
a = np.array([[1, 2 ,3],[4, 5, 6]])
a.resize(3, 3)
print(a)

[[1 2 3]
 [4 5 6]
 [0 0 0]]


#### 6.3 多次元配列を1次元の行列にする

In [98]:
a = np.array([[1, 2 ,3],[4, 5, 6]])
a.ravel()

array([1, 2, 3, 4, 5, 6])

#### 6.4 配列の要素を反対にする

In [106]:
a = np.array([[1, 2 ,3],[4, 5, 6]])
a[::-1,::-1]

array([[6, 5, 4],
       [3, 2, 1]])

#### 6.5 配列を転置する

In [107]:
a = np.array([[1, 2 ,3],[4, 5, 6]])
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

#### 6.6 配列に要素を追加

In [108]:
a = np.array([1, 2, 3])
np.append(a, 4) # 末尾に4を追加

array([1, 2, 3, 4])

In [109]:
np.append(0, a) # 先頭に０を追加

array([0, 1, 2, 3])

#### 6.7 条件を満たす要素を返す、あるいはTrue・Falseを判定する

In [110]:
a = np.arange(6).reshape((2, 3))
np.where(a < 3, True, False) # a<3の場合True、そうでない場合Falseを返す

array([[ True,  True,  True],
       [False, False, False]], dtype=bool)

In [111]:
np.where(a < 3) # a<3を満たす要素の範囲を抽出

(array([0, 0, 0]), array([0, 1, 2]))

#### 6.8 配列の要素が全て条件を満たすか否かを判定する



In [112]:
a = np.arange(6).reshape((2, 3))
np.all(a < 3)

False

In [113]:
np.all(a < 6)

True

#### 6.9 配列の要素のいずれかが条件を満たすか否かを判定する

In [114]:
a = np.arange(6).reshape((2, 3))
np.any(a < 3)

True

In [115]:
np.any(a > 6)

False

#### 6.10 多次元配列の中の最大値の要素を持つインデックスを返す

In [116]:
a = np.array([1, 2, 3])
a.argmax()

2

#### 6.11 配列を小さい順に並べ替える

In [117]:
a = np.array([8, 2, 1, 5, 6])
np.sort(a)

array([1, 2, 5, 6, 8])

#### 6.12 配列を小さい順に並べ替えた際の配列のインデックスを出力

In [118]:
a = np.array([8, 2, 1, 5, 6])
np.argsort(a)

array([2, 1, 3, 4, 0])

#### 6.13 配列に次元を追加

In [119]:
a = np.arange(6).reshape(2, 3)

np.expand_dims(a, 0)

array([[[0, 1, 2],
        [3, 4, 5]]])

In [120]:
np.expand_dims(a, 0).shape 

(1, 2, 3)

In [121]:
np.expand_dims(a, 1)

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [122]:
np.expand_dims(a, 1).shape

(2, 1, 3)

#### 6.14 複数の配列をブロードキャストして形状を揃えたい際に使用する

In [123]:
a = np.arange(3)
b = np.arange(3).reshape(3, 1)
np.broadcast_arrays(a, b)

[array([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]), array([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]])]

### 7.　配列の演算

##### 7.1 一般的な四則演算

In [124]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [125]:
a + b

array([5, 7, 9])

In [126]:
a - b

array([-3, -3, -3])

In [127]:
a * b 

array([ 4, 10, 18])

In [128]:
a / b

array([ 0.25,  0.4 ,  0.5 ])

In [129]:
a **2 # aの2乗

array([1, 4, 9])

#### 7.2 a, bの足し算

In [130]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.add(a,b)

array([5, 7, 9])

#### 7.3 a, bの引き算

In [131]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.subtract(a, b)

array([-3, -3, -3])

#### 7.4 配列の要素の合計値

In [132]:
a = np.array([[1, 2, 3],[4,5,6]])

np.sum(a)

21

In [133]:
np.sum(a, axis=0) #列ごとの合計値

array([5, 7, 9])

In [134]:
np.sum(a, axis=1) #列ごとの合計値

array([ 6, 15])

#### 7.5 a, bの要素ごとの積（アダマール積）

In [135]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.multiply(a,b)

array([ 4, 10, 18])

#### 7.6 a, bの配列同士の積

In [136]:
a = np.arange(3).reshape(1, 3)
b = np.arange(3).reshape(3, 1)

np.dot(a,b)

array([[5]])

#### 7.7 平均の算出

In [137]:
a = np.arange(10).reshape(2, 5)
np.mean(a)

4.5

#### 7.8 標準偏差の算出

In [138]:
a = np.arange(10).reshape(2, 5)
np.std(a)

2.8722813232690143

#### 7.9 累乗の計算

In [139]:
np.power(2,3) #2の３乗

8

In [ ]:
a = np.array([1, 2, 3])
np.power(a, 2)

#### 7.10 平方根の計算

In [143]:
np.sqrt(4) 


2.0

In [142]:
a = np.array([1, 4, 9])
np.sqrt(a) 

array([ 1.,  2.,  3.])

#### 7.11 最大値を返す

In [144]:
a = np.array([1, 2, 3])
np.max(a) 

3

#### 7.12 最小値を返す

In [145]:
a = np.array([1, 2, 3])
np.min(a) 

1

#### 7.13 絶対値を求める

In [146]:
np.abs(-1)

1

##### 7.14 eのx乗

In [147]:
np.exp(1)

2.7182818284590451

#### 7.15 eを底とするxの対数

In [148]:
np.log(1)

0.0

#### 7.16 Sinを求める

In [150]:
np.sin(1)

0.8414709848078965

#### 7.17 Cosを求める

In [151]:
np.cos(1)

0.54030230586813977

##### 7.18 Tanを求める

In [152]:
np.tan(1)

1.5574077246549023

### 8. 配列のメモリサイズの確認

In [5]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


### 9. サイズ10の0ベクトルを作成し5番目の値を1にする

In [153]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


### 10. 10~49の範囲を持つベクトルの作成

In [154]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 11. ベクトルの反転

In [9]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


### 12. 0から8の範囲の値で3x3マトリックスを作成

In [10]:
Z = np.arange(9).reshape(3, 3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 13. リスト[1,2,0,0,4,0]から0でない要素のインデックスを検索

In [11]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


### 14. 3x3単位行列を作成

In [12]:
Z = np.eye(3)
print(Z)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


### 15. ランダムな値で3x3x3配列を作成

In [13]:
Z = np.random.random((3,3,3))
print(Z)

[[[ 0.12300046  0.94627785  0.64969862]
  [ 0.22385867  0.3230708   0.05127255]
  [ 0.89658195  0.69634744  0.37595085]]

 [[ 0.42813568  0.69495868  0.01020449]
  [ 0.24538114  0.88996269  0.94547411]
  [ 0.93803878  0.34386696  0.84911825]]

 [[ 0.44797548  0.41293309  0.29771891]
  [ 0.46883712  0.8347961   0.41214666]
  [ 0.02533876  0.62079972  0.7636406 ]]]


### 16. ランダムな値で10x10の配列を作成し、最小値と最大値を見つける

In [14]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.0108471385642 0.990998430843


### 17.サイズ30のランダムなベクトルを作成し、平均値を見つける

In [15]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.481235925211


### 18. 境界に1、内側に0の2d配列を作成

In [16]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


### 19. 既存の配列の周りに（0で埋められた）境界線を追加

In [20]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)
print("\n")
# Using fancy indexing
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


### 20. 次の式の結果を確認
0 * np.nan<br>
np.nan == np.nan<br>
np.inf > np.nan<br>
np.nan - np.nan<br>
np.nan in set([np.nan])<br>
0.3 == 3 * 0.1<br>

In [21]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


### 21.対角線のすぐ下に値1、2、3、4の5x5行列を作成

In [22]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### 22. 8x8マトリックスを作成し、チェッカーボードパターンで塗りつぶし

In [23]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 23.（6,7,8）形状配列を考える。100番目の要素のインデックス（x、y、z）は何か？

In [24]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


### 24. タイル関数を使用してチェッカーボード8x8マトリックスを作成

In [25]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 25. 5x5のランダム行列を正規化する

In [26]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 0.90325289  0.30072113  0.46846188  0.81713183 -1.49551151]
 [ 0.85485085  1.35083311 -0.30938979 -0.13050063 -0.14870362]
 [-1.42716053 -1.05613164 -1.51353366 -1.2389341  -1.43703017]
 [-0.37137151  0.86123696  0.5003659  -0.23321558  0.62946598]
 [ 1.77607293  1.08180988  0.82217347 -1.53935337  0.53445931]]


### 26. 色を4つの符号なしバイト（RGBA）として記述するカスタムdtypeを作成

In [28]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


### 27. 5x3行列に3x2行列を掛ける（実数行列の積）

In [30]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)
print("\n")
# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

[[ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]]


[[ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]]


### 28. 1D配列が与えられた場合、3から8までのすべての要素を負にする

In [31]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


### 29. 次の式の結果を確認
np.array(0) / np.array(0)<br>
np.array(0) // np.array(0)<br>
np.array([np.nan]).astype(int).astype(float)<br>

In [33]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[ -9.22337204e+18]


/usr/lib/python3/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/lib/python3/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


### 30. フロート配列の四捨五入

In [35]:
Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[ 7.19842287  3.15946677  3.60395887 -1.42117894  5.54893268  6.69202085
  7.77950741  2.25531434  6.41677357  6.01895367]
[ 8.  4.  4. -2.  6.  7.  8.  3.  7.  7.]
[ 8.  4.  4. -2.  6.  7.  8.  3.  7.  7.]


### 31. 2つの配列間で共通の値を見つける

In [36]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[1 5]


### 32.numpy警告を無視する方法

In [37]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

### 33.昨日、今日、明日の日付を取得

In [41]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print("yesterday:{},\ntoday:{},\ntomorrow:{}".format(yesterday, today, tomorrow))

yesterday:2022-03-15,
today:2022-03-16,
tomorrow:2022-03-17


### 34.2016年7月に対応するすべての日付を取得する

In [42]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


### 35.（（A + B）*（-A / 2））をその場で（コピーなしで）計算する方法

In [43]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

### 36. 4つの異なる方法を使用して、正の数のランダム配列の整数部分を抽出

In [45]:
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[ 9.  0.  1.  0.  6.  3.  6.  7.  7.  1.]
[ 9.  0.  1.  0.  6.  3.  6.  7.  7.  1.]
[ 9.  0.  1.  0.  6.  3.  6.  7.  7.  1.]
[9 0 1 0 6 3 6 7 7 1]
[ 9.  0.  1.  0.  6.  3.  6.  7.  7.  1.]


### 37. 0から4の範囲の行値を持つ5x5マトリックスを作成

In [48]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)
print("\n")
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)

[[ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]]


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### 38. 10個の整数を生成し、それを使用して配列を作成するジェネレーター関数

In [49]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


### 39. 0から1の範囲の値でサイズ10のベクトルを作成し、両方を除外

In [50]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[ 0.09090909  0.18181818  0.27272727  0.36363636  0.45454545  0.54545455
  0.63636364  0.72727273  0.81818182  0.90909091]


### 40.サイズ10のランダムなベクトルを作成し、それを並べ替え

In [53]:
Z = np.random.random(10)
Z.sort()
print(Z)

[ 0.10583368  0.14233085  0.16042301  0.2198301   0.40966685  0.58499038
  0.75767604  0.81313305  0.84844748  0.95485645]


### 41.np.sumよりも速く小さな配列を合計する方法

In [54]:
Z = np.arange(10)
np.add.reduce(Z)

45

### 42.2つのランダム配列AとBを比較し、それらが等しいかどうかを確認

In [55]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


### 43.配列を読み取り専用にする

In [155]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

### 44. サイズ10のランダムベクトルを作成し、最大値を0に置き換え

In [57]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[ 0.53996469  0.44767091  0.91008382  0.54623511  0.78715531  0.82834173
  0.20856333  0.75903047  0.54301073  0.        ]


### 45. [0,1]x[0,1]領域をカバーする`x`および`y`座標で構造化配列を作成

In [58]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[( 0.  ,  0.  ) ( 0.25,  0.  ) ( 0.5 ,  0.  ) ( 0.75,  0.  )
  ( 1.  ,  0.  )]
 [( 0.  ,  0.25) ( 0.25,  0.25) ( 0.5 ,  0.25) ( 0.75,  0.25)
  ( 1.  ,  0.25)]
 [( 0.  ,  0.5 ) ( 0.25,  0.5 ) ( 0.5 ,  0.5 ) ( 0.75,  0.5 )
  ( 1.  ,  0.5 )]
 [( 0.  ,  0.75) ( 0.25,  0.75) ( 0.5 ,  0.75) ( 0.75,  0.75)
  ( 1.  ,  0.75)]
 [( 0.  ,  1.  ) ( 0.25,  1.  ) ( 0.5 ,  1.  ) ( 0.75,  1.  )
  ( 1.  ,  1.  )]]


### 46.XとYの2つの配列が与えられた場合、コーシー行列Cを作成します（Cij = 1 /（xi --yj））

In [59]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.16363712


### 47.各numpyスカラータイプの表現可能な最小値と最大値を出力

In [60]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.40282e+38
3.40282e+38
1.19209e-07
-1.79769313486e+308
1.79769313486e+308
2.22044604925e-16


### 48.配列のすべての値を出力する

In [62]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.

### 49. ベクトル内で（特定のスカラーに）最も近い値を見つける方法

In [64]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

98


### 50.位置（x、y）と色（r、g、b）を表す構造化配列を作成

In [65]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[(( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))]


### 51.座標を表す形状（100,2）のランダムなベクトルを考え、ポイントごとの距離を計算

In [67]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[ 0.          0.88898666  0.62848732  0.58049933  0.26478395  0.78150425
   0.75394626  0.36315907  0.82446876  0.63743694]
 [ 0.88898666  0.          0.76653869  0.44906761  0.79526432  0.50882019
   0.251756    0.61473519  0.65339725  0.5223459 ]
 [ 0.62848732  0.76653869  0.          0.33045569  0.36449621  0.3180456
   0.51723475  0.72701731  0.2551161   0.24451815]
 [ 0.58049933  0.44906761  0.33045569  0.          0.39319116  0.22421373
   0.21722861  0.5004765   0.32915001  0.11247979]
 [ 0.26478395  0.79526432  0.36449621  0.39319116  0.          0.55669801
   0.60151977  0.46262463  0.57534186  0.41484478]
 [ 0.78150425  0.50882019  0.3180456   0.22421373  0.55669801  0.
   0.26542799  0.72335559  0.14529237  0.14431653]
 [ 0.75394626  0.251756    0.51723475  0.21722861  0.60151977  0.26542799
   0.          0.57452084  0.41053523  0.27275634]
 [ 0.36315907  0.61473519  0.72701731  0.5004765   0.46262463  0.72335559
   0.57452084  0.          0.82388133  0.60366019]
 [ 0.8244

### 52.浮動小数点（32ビット）配列を整数（32ビット）に変換する方法

In [68]:
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[14 84 82 70 88 27 72 94 91 82]


### 53.一般的な2Dガウスのような配列を生成

In [72]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[ 0.36787944  0.44822088  0.51979489  0.57375342  0.60279818  0.60279818
   0.57375342  0.51979489  0.44822088  0.36787944]
 [ 0.44822088  0.54610814  0.63331324  0.69905581  0.73444367  0.73444367
   0.69905581  0.63331324  0.54610814  0.44822088]
 [ 0.51979489  0.63331324  0.73444367  0.81068432  0.85172308  0.85172308
   0.81068432  0.73444367  0.63331324  0.51979489]
 [ 0.57375342  0.69905581  0.81068432  0.89483932  0.9401382   0.9401382
   0.89483932  0.81068432  0.69905581  0.57375342]
 [ 0.60279818  0.73444367  0.85172308  0.9401382   0.98773022  0.98773022
   0.9401382   0.85172308  0.73444367  0.60279818]
 [ 0.60279818  0.73444367  0.85172308  0.9401382   0.98773022  0.98773022
   0.9401382   0.85172308  0.73444367  0.60279818]
 [ 0.57375342  0.69905581  0.81068432  0.89483932  0.9401382   0.9401382
   0.89483932  0.81068432  0.69905581  0.57375342]
 [ 0.51979489  0.63331324  0.73444367  0.81068432  0.85172308  0.85172308
   0.81068432  0.73444367  0.63331324  0.51979489]
 [

### 54.p要素を2D配列にランダムに配置する

In [73]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
