# Numpy 100本ノック

## PythonのNumPyとは
最初にPythonにおけるNumPyの役割やNumPyを使ってできることを解説します。
まずはNumPyで何ができるのかを理解しましょう。
### NumPyの役割
NumPyは機械学習やディープラーニングを行う際に使われる拡張ライブラリです。ベクトルや行列といった数学的対象を処理するのに便利なライブラリになっています。
基本的な計算処理であればNumPyを使わずともできますが、大量のデータを処理するような場合には処理が遅くなるため、高速な数値計算が必要な場合にはNumPyを使うことが多いです。
つまり、NumPyはベクトルや行列の計算を高速に処理するためのライブラリと覚えておけば大丈夫です。

### Numpyでできること
NumPyを使用することによって、ベクトルや行列の演算、乱数生成など様々なことができるようになります。通常のPythonで処理を行うよりもずっと早く処理できるので、大量のデータを扱う機械学習ではNumPyが利用されるのです。

基本的には、数値計算を高速で行うことができると覚えておけば問題ありません。

### 1. npという名前でnumpyパッケージをインポート (★☆☆)

In [1]:
import numpy as np

### 2. numpyの構成とバージョンを表示

In [2]:
print(np.__version__)
np.show_config()

1.13.3
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
atlas_3_10_blas_threads_info:
  NOT AVAILABLE
atlas_3_10_blas_info:
  NOT AVAILABLE
atlas_blas_threads_info:
  NOT AVAILABLE
atlas_blas_info:
  NOT AVAILABLE
blas_info:
    libraries = ['blas', 'blas']
    library_dirs = ['/usr/lib/x86_64-linux-gnu']
    include_dirs = ['/usr/local/include', '/usr/include']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['blas', 'blas']
    library_dirs = ['/usr/lib/x86_64-linux-gnu']
    include_dirs = ['/usr/local/include', '/usr/include']
    language = c
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
  NOT AVAILABLE
atlas_3_10_info:
  NOT AVAILABLE
atlas_threads_info:
  NOT AVAILABLE
atlas_info:
  NOT AVAILABLE
lapack_info:
    libraries = ['lapack', 'lapack']
    library_dirs = ['/usr/lib/x86_64-li

### 3. サイズが10 nullベクトルの作成

In [4]:
Z = np.zeros(10)
print(Z)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


### 4. 配列のメモリサイズの確認

In [5]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


### 5. サイズ10の0ベクトルを作成し5番目の値を1にする

In [7]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


### 6. 10~49の範囲を持つベクトルの作成

In [8]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 7. ベクトルの反転

In [9]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


### 8. 0から8の範囲の値で3x3マトリックスを作成

In [10]:
Z = np.arange(9).reshape(3, 3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 9. リスト[1,2,0,0,4,0]から0でない要素のインデックスを検索

In [11]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


### 10. 3x3単位行列を作成

In [12]:
Z = np.eye(3)
print(Z)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


### 11. ランダムな値で3x3x3配列を作成

In [13]:
Z = np.random.random((3,3,3))
print(Z)

[[[ 0.12300046  0.94627785  0.64969862]
  [ 0.22385867  0.3230708   0.05127255]
  [ 0.89658195  0.69634744  0.37595085]]

 [[ 0.42813568  0.69495868  0.01020449]
  [ 0.24538114  0.88996269  0.94547411]
  [ 0.93803878  0.34386696  0.84911825]]

 [[ 0.44797548  0.41293309  0.29771891]
  [ 0.46883712  0.8347961   0.41214666]
  [ 0.02533876  0.62079972  0.7636406 ]]]


### 12. ランダムな値で10x10の配列を作成し、最小値と最大値を見つける

In [14]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.0108471385642 0.990998430843


### 13.サイズ30のランダムなベクトルを作成し、平均値を見つける

In [15]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.481235925211


### 14. 境界に1、内側に0の2d配列を作成

In [16]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


### 15. 既存の配列の周りに（0で埋められた）境界線を追加

In [20]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)
print("\n")
# Using fancy indexing
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


### 16. 次の式の結果を確認
0 * np.nan<br>
np.nan == np.nan<br>
np.inf > np.nan<br>
np.nan - np.nan<br>
np.nan in set([np.nan])<br>
0.3 == 3 * 0.1<br>

In [21]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


### 17.対角線のすぐ下に値1、2、3、4の5x5行列を作成

In [22]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### 18.8x8マトリックスを作成し、チェッカーボードパターンで塗りつぶし

In [23]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 19.（6,7,8）形状配列を考える。100番目の要素のインデックス（x、y、z）は何か？

In [24]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


### 20. タイル関数を使用してチェッカーボード8x8マトリックスを作成

In [25]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 21. 5x5のランダム行列を正規化する

In [26]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 0.90325289  0.30072113  0.46846188  0.81713183 -1.49551151]
 [ 0.85485085  1.35083311 -0.30938979 -0.13050063 -0.14870362]
 [-1.42716053 -1.05613164 -1.51353366 -1.2389341  -1.43703017]
 [-0.37137151  0.86123696  0.5003659  -0.23321558  0.62946598]
 [ 1.77607293  1.08180988  0.82217347 -1.53935337  0.53445931]]


### 22. 色を4つの符号なしバイト（RGBA）として記述するカスタムdtypeを作成

In [28]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


### 23.5x3行列に3x2行列を掛ける（実数行列の積）

In [30]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)
print("\n")
# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

[[ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]]


[[ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]]


### 24. 1D配列が与えられた場合、3から8までのすべての要素を負にする

In [31]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


### 25.次の式の結果を確認
np.array(0) / np.array(0)<br>
np.array(0) // np.array(0)<br>
np.array([np.nan]).astype(int).astype(float)<br>

In [33]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[ -9.22337204e+18]


/usr/lib/python3/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/lib/python3/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


### 26. フロート配列の四捨五入

In [35]:
Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[ 7.19842287  3.15946677  3.60395887 -1.42117894  5.54893268  6.69202085
  7.77950741  2.25531434  6.41677357  6.01895367]
[ 8.  4.  4. -2.  6.  7.  8.  3.  7.  7.]
[ 8.  4.  4. -2.  6.  7.  8.  3.  7.  7.]


### 27. 2つの配列間で共通の値を見つける

In [36]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[1 5]


### 28.numpy警告を無視する方法

In [37]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

### 29.昨日、今日、明日の日付を取得

In [41]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print("yesterday:{},\ntoday:{},\ntomorrow:{}".format(yesterday, today, tomorrow))

yesterday:2022-03-15,
today:2022-03-16,
tomorrow:2022-03-17


### 30.2016年7月に対応するすべての日付を取得する

In [42]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


### 31.（（A + B）*（-A / 2））をその場で（コピーなしで）計算する方法

In [43]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

### 32. 4つの異なる方法を使用して、正の数のランダム配列の整数部分を抽出

In [45]:
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[ 9.  0.  1.  0.  6.  3.  6.  7.  7.  1.]
[ 9.  0.  1.  0.  6.  3.  6.  7.  7.  1.]
[ 9.  0.  1.  0.  6.  3.  6.  7.  7.  1.]
[9 0 1 0 6 3 6 7 7 1]
[ 9.  0.  1.  0.  6.  3.  6.  7.  7.  1.]


### 33. 0から4の範囲の行値を持つ5x5マトリックスを作成

In [48]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)
print("\n")
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)

[[ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]]


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### 34. 10個の整数を生成し、それを使用して配列を作成するジェネレーター関数

In [49]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


### 35.0から1の範囲の値でサイズ10のベクトルを作成し、両方を除外

In [50]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[ 0.09090909  0.18181818  0.27272727  0.36363636  0.45454545  0.54545455
  0.63636364  0.72727273  0.81818182  0.90909091]
